version: '2'
services:
  spotihax: # Main
    build: .
    environment:
      SLACK_TOKEN: 'xoxp-11545145989-33387319376-121976294001-e7edd13fb2622c230e617d0ead156fc1'
      SPOTIFY_CLIENT_ID: ab12cdf455b94f6d82d7230d39f87387
      SPOTIFY_CLIENT_SECRET: 4cb67fab23234adcb37d97a2dc4c4790
      NODE_ENV: 'development'
      PORT: 8000
    volumes:
      - ./src:/home/node/app/src
      - ./scripts:/home/node/app/scripts
      - ./package.json:/home/node/app/package.json
      - ./yarn.lock:/home/node/app/yarn.lock
      - ./.nycrc:/home/node/app/.nycrc
      - ./coverage:/home/node/app/coverage
    ports:
      - 443:8000
      - 9222:9222
